// <auto-generated />
namespace WechatPayPlatform.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class udRechargeBillDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(udRechargeBillDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201505051658504_udRechargeBillDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
