// <auto-generated />
namespace WechatPayPlatform.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addWorkTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addWorkTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201507201136421_addWorkTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
